
spring:
  main:
    banner-mode: "console"
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  resources:
    chain:
      strategy:
        content:
          enabled: false
      cache: false
      compressed: false
    cache:
      period: 86400